### ISSUE TITLE
Install custom helm plugins

### ISSUE THREAD

**Issue by adri** [mamezou-tech/setup-helmfile#13]
Idea: Would be cool to install custom plugins for helm as well.

**Comment by kondoumh** [comment]
The current version installs the following plug-ins, is there anything else you need?

- helm-diff
- helm-s3

**Comment by kriptor** [comment]
> The current version installs the following plug-ins, is there anything else you need?
> 
> * helm-diff
> * helm-s3

helm-git
secrets

**Comment by manuelvanrijn** [comment]
@kriptor The way I did it was by installing it after this action

```yaml
-
  name: Install helm-secret plugin
  run: helm plugin install https://github.com/zendesk/helm-secrets
-
  name: Import GPG key
  id: staging_gpg
  uses: crazy-max/ghaction-import-gpg@v3
  with:
    gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
-
  name: GPG user IDs
  run: |
    echo "fingerprint: ${{ steps.staging_gpg.outputs.fingerprint }}"
    echo "keyid:       ${{ steps.staging_gpg.outputs.keyid }}"
    echo "name:        ${{ steps.staging_gpg.outputs.name }}"
```
