### ISSUE TITLE
helm diff plugin not installed by default

### ISSUE THREAD

**Issue by esvirskiy** [mamezou-tech/setup-helmfile#17]
As per docs, it should be installed by default. I am getting the following error message

```
Error: unknown command "diff" for "helm"
```

My code below

```
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.5.0
        with:
          helmfile-version: "v0.98.2"
          helm-version: "v2.15.1"
      - name: Deploy to Production
        run: helmfile -f operations/helm/releases/production.yaml.gotmpl apply
```

EDIT: same deal with `mamezou-tech/setup-helmfile@v0.6.0`
